### ISSUE TITLE
can't compile plugins

### ISSUE THREAD

**Issue by 2389736818** [oylsister/sm-zombieriot-2#1]
![zrerror](https://user-images.githubusercontent.com/10596760/150634326-ea85f840-5adf-4988-8323-1f5bfe2be2dd.jpg)

**Comment by oylsister** [comment]
Try compiling in SM 1.10

**Comment by 2389736818** [comment]
still can't compile
![20220127103549961](https://user-images.githubusercontent.com/10596760/151300644-38bf45cb-0733-467b-90d3-4081b51d2fed.jpg)

But there is a solution
It is to change the 'int' and '&allowed' of sayhooks.inc to 'void and 'allowed'
![20220127103739093](https://user-images.githubusercontent.com/10596760/151300659-e9adde17-f9ad-406a-aca0-a02e5bd64037.jpg)
