### ISSUE TITLE
Humans class

### ISSUE THREAD

**Issue by WareZ57** [oylsister/sm-zombieriot-2#2]
Hello,
I try so hard to change the skins of humans but nothing seems to work, as well as the skins, that life doesn’t work..

Skins are download, but they do not apply in game

![image](https://user-images.githubusercontent.com/7504466/154829568-2765219d-e336-40bd-a024-981060d737de.png)

Any idea ?

Thanks you.

**Comment by oylsister** [comment]
this plugin hasn't been properly tested for 100%, but I do have a plan to fix all stuff on May

**Comment by oylsister** [comment]
Human Class should be fine now
