### ISSUE TITLE
TerminateRound not working in linux

### ISSUE THREAD

**Issue by pizzadox11** [oylsister/sm-zombieriot-2#5]
i dont know what did you do with TerminateRound but it wont work in linux, the round never ends

**Comment by pizzadox11** [comment]
i dont think its linux related but on css its broken

**Comment by oylsister** [comment]
> i dont know what did you do with TerminateRound but it wont work in linux, the round never ends

The original TeminateRound they call signature individuals on their plugin instead of using already existed function from sourcemod "CS_TerminateRound" also this plugin is tended to work for csgo. I don't know much about css

**Comment by oylsister** [comment]
I recently have tried on css linux, but they worked just fine.
